# Generated by Django 6.0.2 on 2026-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_pdf_file_book_price_book_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='square_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
