# Generated by Django 6.0.2 on 2026-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_order_square_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='square_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
