# Generated by Django 6.0.2 on 2026-03-28 13:47

import books.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, storage=books.storage_backends.PublicMediaStorage(), upload_to='books/cover/'),
        ),
    ]
