"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environs import Env
from datetime import timedelta

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	# my apps.
	'books.apps.BooksConfig',
	'accounts.apps.AccountsConfig',

	# default apps.
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	"whitenoise.runserver_nostatic",
	'django.contrib.staticfiles',
	'django.contrib.sites',

	#third-party apps.
	'rest_framework',
	'rest_framework.authtoken',
	'drf_spectacular',
	'drf_spectacular_sidecar',
	'storages',


	#auth
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.google',

	'dj_rest_auth',
	'dj_rest_auth.registration',
]

MIDDLEWARE = [
	"allauth.account.middleware.AccountMiddleware", # allauth
	'django.middleware.security.SecurityMiddleware',
	"whitenoise.middleware.WhiteNoiseMiddleware",
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
	"default": {
		"BACKEND": 'storages.backends.s3boto3.S3Boto3Storage',
	},
	"staticfiles": {
		"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
	},
}

# Custom settings.
#_______________________________________________________________________________________

# custom user.
AUTH_USER_MODEL = "accounts.CustomUser"

# rest_framework.
REST_FRAMEWORK = {

	'DEFAULT_AUTHENTICATION_CLASSES': [
		'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
		'rest_framework.authentication.SessionAuthentication', # Optional, good for browsable API
	],

	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.AllowAny',
	],

	'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
REST_AUTH = {
	'USE_JWT': True,
	'JWT_AUTH_COOKIE': 'bookapi-auth',
	'JWT_AUTH_REFRESH_COOKIE': 'bookapi-refresh-token',
	'JWT_AUTH_HTTPONLY': not DEBUG,
	'JWT_AUTH_SECURE': not DEBUG,
}

# simple jwt.

SIMPLE_JWT = {
	"ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
	"REFRESH_TOKEN_LIFETIME": timedelta(days=1),
	"AUTH_HEADER_TYPES": ("Bearer",),
}

# for user uploaded media.
AWS_S3_CUSTOM_DOMAIN = env("S3_CUSTOM_DOMAIN")
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
MEDIA_ROOT = BASE_DIR / "media"


# for allauth 
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
	
	# Needed to login by username in Django admin, regardless of `allauth`
	'django.contrib.auth.backends.ModelBackend',

	# `allauth` specific authentication methods, such as login by email
	'allauth.account.auth_backends.AuthenticationBackend',
	
]

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['username',"email*", "password1*"]

ACCOUNT_EMAIL_VERIFICATION = 'none' # for email verification
LOGIN_URL = '/api/v1/auth/login/'
LOGIN_REDIRECT_URL = '/auth/token/'

SOCIALACCOUNT_PROVIDERS = {
	'google': {
		'APP': {
			'client_id': env('GOOGLE_CLIENT_ID'),
			'secret': env('GOOGLE_CLIENT_SECRET'),
			'key': '' # Leave empty for Google
		},
		'SCOPE': ['profile', 'email'],
		'AUTH_PARAMS': {'access_type': 'online'},
		'OAUTH_PKCE_ENABLED': True,
	}
}
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_ADAPTER = "accounts.adapters.CustomSocialAccountAdapter"

SQUARE_APPLICATION_ID = env("SQUARE_APPLICATION_ID")
SQUARE_ACCESS_TOKEN = env("SQUARE_ACCESS_TOKEN")
SQUARE_ENVIRONMENT = env("SQUARE_ENVIRONMENT")
SQUARE_LOCATION_ID = env("SQUARE_LOCATION_ID")
SQUARE_WEBHOOK_SIGNATURE_KEY = env("SQUARE_WEBHOOK_SIGNATURE_KEY")

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#cookies
if not DEBUG:
	SESSION_COOKIE_SECURE = True
	CSRF_COOKIE_SECURE = True
	SESSION_COOKIE_HTTPONLY = True
	CSRF_COOKIE_HTTPONLY = False  # must be False for DRF browsable API
	SESSION_COOKIE_SAMESITE = "None"
	CSRF_COOKIE_SAMESITE = "None"

#HTTPS
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)

SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=2592000)  # 30 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
	"SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=True)

#cache
CACHES = {
	"default": {
		"BACKEND": "django.core.cache.backends.locmem.LocMemCache",
	}
}

#Cloud S3 Storage.
AWS_ACCESS_KEY_ID = env("S3_Access_key_ID")
AWS_SECRET_ACCESS_KEY = env("S3_Secret_Access_Key")
AWS_STORAGE_BUCKET_NAME = env("S3_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = env("S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = 'ap-southeast-2' 

SUPABASE_URL = env("SUPABASE_URL")
SUPABASE_SERVICE_KEY = env("SUPABASE_SERVICE_KEY")
SUPABASE_PUBLIC_BUCKET = env("SUPABASE_PUBLIC_BUCKET")